# Ini yang saya pake sekarang cuman docker compose services aja karena untuk DB udah ada container global

services:
  services:
    build: .
    image: fastify_services:dev
    container_name: fastify_services
    env_file: .env
    ports:
      - "3333:3333"
    networks:
      - postgres_network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  postgres_network:
    external: true
