# Ini kemarin saya buat testing pake docker compose include services + DBnya

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  services:
    build: .
    container_name: fastify_services
    env_file: .env
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
